%column_one
columnAsList(Board, 1, AsRow),
getCube(Board, 1, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_two
columnAsList(Board, 2, AsRow),
getCube(Board, 2, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_three
columnAsList(Board, 3, AsRow),
getCube(Board, 3, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_four
columnAsList(Board, 4, AsRow),
getCube(Board, 4, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
(var(X)) ,digit(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_five
columnAsList(Board, 5, AsRow),
getCube(Board, 5, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_six
columnAsList(Board, 6, AsRow),
getCube(Board, 6, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_seven
columnAsList(Board, 7, AsRow),
getCube(Board, 7, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X),

%column_eight
columnAsList(Board, 8, AsRow),
getCube(Board, 8, ContentsOfCube),
nth0(0, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(0,Board,X),
is_set(X),

nth0(1, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(1,Board,X),
is_set(X), 

nth0(2, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(2,Board,X),
is_set(X),

nth0(3, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(3,Board,X),
is_set(X),

nth0(4, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(4,Board,X),
is_set(X),

nth0(5, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(5,Board,X),
is_set(X),

nth0(6, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(6,Board,X),
is_set(X),

nth0(7, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(7,Board,X),
is_set(X),

nth0(8, AsRow, X),
var(X) -> digit(X) ;  nonvar(X),
is_set(AsRow),
is_set(ContentsOfCube),
nth0(8,Board,X),
is_set(X).
